services:
  ytdownloader_db:
    image: postgres:15-alpine
    container_name: ytdownloader_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"
    volumes:
      - ytdownloader_db_data:/var/lib/postgresql/data
    networks:
      - ytdownloader_network
    restart: unless-stopped

  ytdownloader_minio:
    image: minio/minio:latest
    container_name: ytdownloader_minio
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    networks:
      - ytdownloader_network
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ytdownloader_minio_data:/data
    restart: unless-stopped

networks:
  ytdownloader_network:
    driver: bridge
    name: ytdownloader_network

volumes:
  ytdownloader_db_data:
    name: ytdownloader_db_data
  ytdownloader_minio_data:
    name: ytdownloader_minio_data
