global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'apigateway'
    static_configs:
      - targets: ['apigateway:5000']

  - job_name: 'authservice'
    static_configs:
      - targets: ['authservice:5000']

  - job_name: 'k6'
    static_configs:
      - targets: ['k6:6565']
